export const NOTIFICATION_NEW_MESSAGE = 'NOTIFICATION_NEW_MESSAGE';
export const NOTIFICATION_NEW_FOLLOWER = 'NOTIFICATION_NEW_FOLLOWER';

export const NOTIFICATION_NEW_REPORT = 'NOTIFICATION_NEW_REPORT';
