export const SET_PROFILE_STATS = 'SET_PROFILE_STATS';
export const INCREMENT_USER_TASK = 'INCREMENT_USER_TASK';
export const DECREMENT_USER_TASK = 'DECREMENT_USER_TASK';
export const INCREMENT_REPORT = 'INCREMENT_USER_REPORT';
export const DECREMENT_USER_REPORT = 'DECREMENT_USER_REPORT';
