export const SET_REPORTS = "SET_REPORTS";
export const ALL_REPORTS_FOR_TOP = 'ALL_REPORTS_FOR_TOP'
export const CURRENT_TASK_REPORTS = 'CURRENT_TASK_REPORTS'
export const SET_REPORT = 'SET_REPORT';
export const SET_COMMENT = 'SET_COMMENT';
