export const SET_REPORTS = 'SET_REPORTS';
export const ALL_REPORTS_FOR_TOP = 'ALL_REPORTS_FOR_TOP';
export const REPORTS_FOR_TOP_SORTED_BY_COMMENTS = 'REPORTS_FOR_TOP_SORTED_BY_COMMENTS';
export const REPORTS_FOR_TOP_SORTED_BY_LIKES = 'REPORTS_FOR_TOP_SORTED_BY_LIKES';
export const CURRENT_TASK_REPORTS = 'CURRENT_TASK_REPORTS';
export const SET_REPORT = 'SET_REPORT';
export const SET_COMMENT = 'SET_COMMENT';
