export const SET_SUBSCRIBES = 'SET_SUBSCRIBES';
export const ADD_SUBSCRIBE = 'ADD_SUBSCRIBE';
export const DELETE_SUBSCRIBE = 'DELETE_SUBSCRIBE';
export const SUBSCRIBE_ON_USER = 'SUBSCRIBE_ON_USER';
export const UNSUBSCRIBE_FROM_USER = 'UNSUBSCRIBE_FROM_USER';
